name = "tandemx_client"
version = "1.0.0"
target = "javascript"

[dependencies]
gleam_stdlib = "~> 0.32"
lustre = "~> 4.6"
gleam_http = ">= 3.7.2 and < 4.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
lustre_dev_tools = ">= 1.6.2 and < 2.0.0" 

