name = "tandemx_client"
version = "1.0.0"
target = "javascript"

[dependencies]
gleam_stdlib = "~> 0.60.0"
lustre = "~> 5.1.0"
gleam_http = "~> 4.0.0"
gleam_json = "~> 3.0.1"
gleam_javascript = "~> 1.0.0"
supabase = { path = "../supabase" }


[dev-dependencies]
gleeunit = "~> 1.0"
lustre_dev_tools = "~> 1.8.1"
# lustre_dev_tools = { path = "../dev-tools" }
