name = "tandemx_client"
version = "1.0.0"
target = "javascript"

[dependencies]
gleam_stdlib = ">= 0.55.0 and < 2.0.0"
lustre = ">= 4.8.0"
gleam_http = ">= 4.0.0"
gleam_json = ">= 1.0.0"


[dev-dependencies]
gleeunit = ">= 1.0.0"
lustre_dev_tools = ">= 1.7.0"

