version: '3.8'

services:
  postgres:
    image: postgres:14
    environment:
      POSTGRES_DB: tandemx
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "54321:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  electric:
    image: electricsql/electric:latest
    environment:
      DATABASE_URL: postgresql://postgres:password@postgres:5432/tandemx
      PG_PROXY_PASSWORD: proxy_password
      ELECTRIC_WRITE_TO_PG_MODE: direct
    ports:
      - "5133:5133"
      - "3000:3000"
    depends_on:
      - postgres

volumes:
  postgres_data: 