name = "tandemx"
version = "1.0.0"
target = "javascript"

[dependencies]
gleam_stdlib = "~> 0.32"
gleam_http = "~> 3.5"
mist = "~> 0.14"
simplifile = "~> 1.0"
gleam_json = "~> 0.7"
gleam_erlang = "~> 0.24"
supabase = "~> 0.2"
lustre = "~> 4.6.4"

[dev-dependencies]
gleeunit = "~> 1.0"

[javascript]
typescript_declarations = true

[javascript.modules]
todomvc = "./client/src/todomvc"
cards = "./client/src/cards"
contracts = "./client/src/contracts"
divvyqueue = "./client/src/divvyqueue"
nav = "./client/src/components/nav"
form_analyzer = "./client/src/form_analyzer"
constructs = "./client/src/constructs"
chartspace = "./client/src/chartspace"