name = "tandemx"
version = "1.0.0"
target = "javascript"

[dependencies]
gleam_stdlib = ">= 0.60.0"
lustre = "5.1.0"
gleam_http = "~> 4.0.0"
mist = "~> 4.0.7"
simplifile = "~> 2.2.1"
gleam_json = "3.0.1"
gleam_erlang = ">= 0.34.0"
supabase = { path = "./supabase" }
glibsql = "~> 0.8.0"
glenvy = ">= 2.0.0 and < 3.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0"

[javascript]
typescript_declarations = true

[javascript.modules]
todomvc = "./client/src/todomvc"
cards = "./client/src/cards"
contracts = "./client/src/contracts"
divvyqueue = "./client/src/divvyqueue"
nav = "./client/src/components/nav"
form_analyzer = "./client/src/form_analyzer"
constructs = "./client/src/constructs"
chartspace = "./client/src/chartspace"
access_content = "./client/src/access_content"
