name = "tandemx_server"
version = "1.0.0"

target = "erlang"

[dependencies]
gleam_stdlib = "~> 0.60.0"
gleam_http = "~> 4.0.0"
simplifile = "~> 2.2.1"
gleam_bitwise = "~> 1.3"
argv = "~> 1.0"
mist = "~> 4.0.7"
gleam_erlang = "~> 0.34"
snag = "~> 1.1.0"
gleam_regexp = "~> 1.1.1"
gleam_httpc = "~> 4.1.1"
gleam_json = "~> 3.0.1"
wisp = "~> 1.7.0"
supabase = { path = "../supabase/erlang" }
glenvy = ">= 2.0.0 and < 3.0.0"
gleam_otp = ">= 0.16.1 and < 1.0.0"
# pog = "~> 3.2.0"
glibsql = "~> 0.8.0"


[dev-dependencies]
