name = "tandemx_server"
version = "1.0.0"

target = "erlang"

[dependencies]
gleam_stdlib = ">= 0.55.0 and < 2.0.0"
gleam_http = "~> 3.5"
simplifile = "~> 1.0"
gleam_bitwise = "~> 1.3"
argv = "~> 1.0"
mist = "~> 4.0.6"
gleam_erlang = "~> 0.24"
snag = "~> 1.1.0"
glisten = "~> 7.0.1"
gleam_regexp = ">= 1.1.0 and < 2.0.0"
jsx = "~> 3.1"
json = ">= 1.4.1 and < 2.0.0"
gleam_httpc = "~> 2.0"
gleam_json = "~> 2.3.0"

[dev-dependencies]
