name = "supabase"
version = "0.1.0"
target = "erlang"

description = "A Gleam library for Supabase client operations."
licences = ["Apache-2.0"]

[dependencies]
gleam_stdlib = "0.60.0"
gleam_http = "~> 4.0.0"
gleam_httpc = "~> 4.1.0"
gleam_json = "~> 3.0.1"
snag = "~> 1.1"

[dev-dependencies]
gleeunit = "~> 1.0"
